export const BAG_ADD_ITEM = "BAG_ADD_ITEM";
export const BAG_REMOVE_ITEM = "BAG_REMOVE_ITEM";
export const BAG_SAVE_SHIPPING_INFO = "BAG_SAVE_SHIPPING_INFO";

export const BAG_SAVE_PAYMENT_METHOD = "BAG_SAVE_PAYMENT_METHOD";
export const BAG_CLEAR_ITEMS = "BAG_CLEAR_ITEMS";
export const BAG_RESET = "BAG_RESET";
